version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test-osx:
    parameters:
      python-version:
        type: string

    macos:
      xcode: "12.2.0"

    environment:
      # Force (lie about) macOS 10.9 binary compatibility.
      # Needed for properly versioned wheels.
      # See: https://github.com/MacPython/wiki/wiki/Spinning-wheels
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
      - checkout

      - run:
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
            - pyenv-{{ .Environment.CIRCLE_JOB }}-xcode12.2.0

      - run:
          name: install python
          command: |
            pyenv install << parameters.python-version>> -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-{{ .Environment.CIRCLE_JOB }}-xcode12.2.0

      - run: &osx-install-template
          name: install
          command: |
            eval "$(pyenv init -)"
            pyenv local << parameters.python-version >>
            python -m pip install virtualenv
            python -m virtualenv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install -r tests/requirements.txt

      - run: &unix-build-ext-template
          name: build
          command: |
            . env/bin/activate
            python setup.py build_ext --inplace

      - run:
          name: run tests
          command: |
            . env/bin/activate
            python --version
            coverage run -m unittest discover

      - run:
          name: codecov
          command: |
            . env/bin/activate
            codecov

  deploy-osx:
    parameters:
      python-version:
        type: string

    macos:
      xcode: "12.2.0"

    environment:
      # Force (lie about) macOS 10.9 binary compatibility.
      # Needed for properly versioned wheels.
      # See: https://github.com/MacPython/wiki/wiki/Spinning-wheels
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
      - checkout

      - run:
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
            - pyenv-{{ .Environment.CIRCLE_JOB }}-xcode12.2.0

      - run:
          name: install python
          command: |
            pyenv install << parameters.python-version>> -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-{{ .Environment.CIRCLE_JOB }}-xcode12.2.0

      - run: *osx-install-template

      - run:
          name: create bdist_wheel
          command: |
            . env/bin/activate
            python setup.py bdist_wheel

      - run:
          name: deploy
          command: |
            . env/bin/activate
            python -m pip install twine
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing ./dist/*

  test-win:
    parameters:
      python-version:
        type: string
      architecture:
        type: string

    executor:
      name: win/default

    environment:
      CL: /d2FH4-

    steps:
      - checkout

      - run: &win-install-python-template
          name: install python and create virtualenv
          command: |
            nuget install python<< parameters.architecture >> -Version << parameters.python-version >> -ExcludeVersion -OutputDirectory .
            .\python<< parameters.architecture >>\tools\python.exe --version
            .\python<< parameters.architecture >>\tools\python.exe -m pip install virtualenv
            .\python<< parameters.architecture >>\tools\python.exe -m virtualenv env

      - run: &win-install-dependencies-template
          name: install dependencies
          command: |
            env\Scripts\activate.ps1
            python --version
            pip install -r requirements.txt
            pip install -r tests\requirements.txt

      - run:
          name: build extension
          command: |
            env\Scripts\activate.ps1
            python setup.py build_ext --inplace

      - run:
          name: run unittests
          command: |
            env\Scripts\activate.ps1
            coverage run -m unittest discover

      - run:
          name: codecov
          command: |
            env\Scripts\activate.ps1
            codecov

  deploy-win:
    parameters:
      python-version:
        type: string
      architecture:
        type: string

    executor:
      name: win/default

    environment:
      CL: /d2FH4-

    steps:
      - checkout

      - run: *win-install-python-template

      - run: *win-install-dependencies-template

      - run:
          name: create wheel
          command: |
            env\Scripts\activate.ps1
            python setup.py bdist_wheel

      - store_artifacts:
          path: ./dist

      - run: &win-twine-template
          name: install twine and deploy
          command: |
            env\Scripts\activate.ps1
            python -m pip install twine
            twine upload -u $env:PYPI_USERNAME -p $env:PYPI_PASSWORD --skip-existing ./dist/*

  #
  # cpp tests
  #

  # test-linux-cpp11:
  #   docker:
  #     # just use a python image, all we really want is debian
  #     - image: circleci/python:3.8-buster
    
  #   working_directory: ~/repo

  #   steps:
  #     - checkout

  #     - restore_cache: *restore-cache-env

  #     - run: *create-virtualenv

  #     - run: *install-requirements

  #     - save_cache: *save-cache-env

  #     - run:
  #         name: run cpp tests
  #         command: |
  #           . env/bin/activate
  #           make -C testscpp/ --always-make

  #
  # docs
  #

  # test-docs:
  #   docker:
  #     - image: circleci/python:3.7

  #   steps:
  #     - checkout

  #     - restore_cache: *restore-cache-env

  #     - run: *create-virtualenv

  #     - run:
  #         name: install doxygen
  #         command: sudo apt-get install doxygen

  #     - run: *install-requirements

  #     - save_cache: *save-cache-env

  #     - run: *build-extension

  #     - run:
  #         name: Install package
  #         command: env/bin/pip install .

  #     - run: &build-docs
  #         name: Build docs
  #         command: |
  #           . env/bin/activate
  #           make -C docs/ cpp html

  #     - store_artifacts: &save-docs
  #         path: ./docs/build/html

  #     - run: &run-doctest
  #         name: Test docs
  #         command: |
  #           . env/bin/activate
  #           make -C docs/ doctest

workflows:
  version: 2
  test:
    jobs:
      - test-osx:
          matrix:
            parameters:
              python-version: ["3.6.8", "3.7.5", "3.8.6", "3.9.0"]
      - test-win:
          matrix:
            parameters:
              python-version: ["3.6.8", "3.7.5", "3.8.6", "3.9.0"]
              architecture: ["", "x86"]
      # - test-linux-cpp11
      # - test-docs

  deploy:
    jobs:
      - deploy-osx:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
          matrix:
            parameters:
              python-version: ["3.6.8", "3.7.5", "3.8.6", "3.9.0"]
      - deploy-win:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
          matrix:
            parameters:
              python-version: ["3.6.8", "3.7.5", "3.8.6", "3.9.0"]
              architecture: ["", "x86"]
